spring:
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
    password: wolf168
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8082
topics: data-temperature, data-power, data-voltage

